# Generated by Django 2.0 on 2018-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
